### ISSUE TITLE
Not working with styleline 16.3.0

### ISSUE THREAD

**Issue by andrmoel** [stylus/stylelint-stylus#29] opened 2024-03-25 07:52 UTC
I recently upgraded `stylelint` from 16.2.1 to 16.3.0 and using stylelint-stylus throws an error:

```
$ stylelint "**/*.scss"
Error: No configuration provided for /home/foo/bar.scss
```

**Comment by andrmoel** [comment] 2024-03-25 07:58
This has nothing to do with scss.
Let's change it to css. The behavor is the same ;)

package.json

```
    "stylelint": "^16.3.0",
    "stylelint-config-standard": "^36.0.0",
    "stylelint-stylus": "^1.0.0",
 ```
 
 .stylelintrc.json
 
 ```
 {
  "extends": [
    "stylelint-config-standard",
    "stylelint-stylus/standard"
  ]
}
```
 
 Command to execute:
 
 ```
 $ npx stylelint "**/*.css"
Error: No configuration provided for /home/foo/bar.css
```

**Comment by ota-meshi** [comment] 2024-03-25 11:00
I can't reproduce the problem well. Could you please provide a repo that reproduces the problem?

**Comment by andrmoel** [comment] 2024-03-25 12:00
Sure. You are welcome: https://github.com/andrmoel/fix_stylus

**Comment by Moloko20** [comment] 2024-03-25 15:36
Same error for me. I upgrade `stylelint` from 15.6.0 to 16.3.0 and get error:

![image](https://github.com/stylus/stylelint-stylus/assets/66438971/19dc7a11-b49a-450e-9c56-41587b02b7c9)

**Comment by ota-meshi** [comment] 2024-03-25 23:38
I debugged it and it doesn't even load the `stylelint-stylus/standard` entry point js file. It could be a bug in stylelint itself 🤔

**Comment by ota-meshi** [comment] 2024-03-25 23:43
The current workaround is to change the configuration file to a js file so that it clearly tells the path of the js that is the entry point.

```js
module.exports = {
  "extends": [
    "stylelint-config-standard",
    require.resolve("stylelint-stylus/standard")
  ]
}
```

**Comment by ota-meshi** [comment] 2024-03-26 00:14
The cause seems to be the same as this issue:
https://github.com/stylelint/stylelint/issues/7576

**Comment by ota-meshi** [comment] 2024-03-26 05:00
The fix has been merged, please wait for the stylelint patch release.

**Closed by ota-meshi** 2024-03-26 05:00 UTC
Labels: upstream issue

**Comment by andrmoel** [comment] 2024-03-26 06:26
Thank you!
